"""initial_schema

Revision ID: 32cca56f5ac2
Revises:
Create Date: 2026-04-20 17:01:22.658775

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "32cca56f5ac2"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=50), nullable=False),
        sa.Column("google_sub", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_google_sub"), "users", ["google_sub"], unique=True)
    op.create_table(
        "engagement_templates",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("default_scope_config", postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column("default_modules", postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_engagement_templates_created_by"),
        "engagement_templates",
        ["created_by"],
        unique=False,
    )
    op.create_table(
        "engagements",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("client_name", sa.String(length=255), nullable=False),
        sa.Column("sponsor", sa.String(length=255), nullable=False),
        sa.Column("team_count", sa.Integer(), nullable=False),
        sa.Column("kickoff_date", sa.Date(), nullable=False),
        sa.Column("target_delivery_date", sa.Date(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("created_by", sa.String(length=255), nullable=False),
        sa.Column("template_id", sa.UUID(), nullable=True),
        sa.Column("scope_definition", postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["engagement_templates.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_engagements_template_id"), "engagements", ["template_id"], unique=False
    )
    op.create_table(
        "artifacts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("engagement_id", sa.UUID(), nullable=False),
        sa.Column("filename", sa.String(length=500), nullable=False),
        sa.Column("content_type", sa.String(length=100), nullable=False),
        sa.Column("s3_key", sa.String(length=1000), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=50), nullable=False),
        sa.Column("scan_status", sa.String(length=50), nullable=False),
        sa.Column("extracted_text", sa.Text(), nullable=True),
        sa.Column("uploaded_by", sa.UUID(), nullable=False),
        sa.Column(
            "uploaded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["engagement_id"], ["engagements.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["uploaded_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_artifacts_engagement_id"), "artifacts", ["engagement_id"], unique=False
    )
    op.create_index(op.f("ix_artifacts_uploaded_by"), "artifacts", ["uploaded_by"], unique=False)
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("engagement_id", sa.UUID(), nullable=True),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("resource_type", sa.String(length=100), nullable=True),
        sa.Column("resource_id", sa.String(length=255), nullable=True),
        sa.Column("detail", postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["engagement_id"], ["engagements.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_logs_action"), "audit_logs", ["action"], unique=False)
    op.create_index(op.f("ix_audit_logs_created_at"), "audit_logs", ["created_at"], unique=False)
    op.create_index(
        op.f("ix_audit_logs_engagement_id"), "audit_logs", ["engagement_id"], unique=False
    )
    op.create_index(op.f("ix_audit_logs_user_id"), "audit_logs", ["user_id"], unique=False)
    op.create_table(
        "connectors",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("engagement_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("credentials_ref", sa.String(length=500), nullable=False),
        sa.Column("scope_config", postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column("config", postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("last_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["engagement_id"], ["engagements.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_connectors_engagement_id"), "connectors", ["engagement_id"], unique=False
    )
    op.create_table(
        "deliverables",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("engagement_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("content", postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column("locked_by", sa.UUID(), nullable=True),
        sa.Column("locked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["engagement_id"], ["engagements.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["locked_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_deliverables_engagement_id"), "deliverables", ["engagement_id"], unique=False
    )
    op.create_table(
        "exports",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("engagement_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("s3_prefix", sa.String(length=1000), nullable=True),
        sa.Column("file_manifest", postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column("provenance", postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column("exported_by", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["engagement_id"], ["engagements.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["exported_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_exports_engagement_id"), "exports", ["engagement_id"], unique=False)
    op.create_index(op.f("ix_exports_exported_by"), "exports", ["exported_by"], unique=False)
    op.create_table(
        "interviews",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("engagement_id", sa.UUID(), nullable=False),
        sa.Column("interviewee_role", sa.String(length=100), nullable=False),
        sa.Column("interview_date", sa.Date(), nullable=False),
        sa.Column("consent_given", sa.Boolean(), nullable=False),
        sa.Column("notes_md", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["engagement_id"], ["engagements.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_interviews_created_by"), "interviews", ["created_by"], unique=False)
    op.create_index(
        op.f("ix_interviews_engagement_id"), "interviews", ["engagement_id"], unique=False
    )
    op.create_table(
        "scores",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("engagement_id", sa.UUID(), nullable=False),
        sa.Column("dimension", sa.String(length=50), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("stage", sa.Integer(), nullable=False),
        sa.Column("confidence", sa.String(length=10), nullable=False),
        sa.Column("rubric_version", sa.String(length=50), nullable=False),
        sa.Column("evidence_ids", postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column("overrides", postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "computed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("computed_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["computed_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["engagement_id"], ["engagements.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_scores_dimension"), "scores", ["dimension"], unique=False)
    op.create_index(op.f("ix_scores_engagement_id"), "scores", ["engagement_id"], unique=False)
    op.create_table(
        "surveys",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("engagement_id", sa.UUID(), nullable=False),
        sa.Column("template_version", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("modules_enabled", postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column("questions", postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column("distribution_config", postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["engagement_id"], ["engagements.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_surveys_engagement_id"), "surveys", ["engagement_id"], unique=False)
    op.create_table(
        "connector_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("connector_id", sa.UUID(), nullable=False),
        sa.Column("engagement_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("records_written", sa.Integer(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("checkpoint", postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["connector_id"], ["connectors.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["engagement_id"], ["engagements.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_connector_runs_connector_id"), "connector_runs", ["connector_id"], unique=False
    )
    op.create_index(
        op.f("ix_connector_runs_engagement_id"), "connector_runs", ["engagement_id"], unique=False
    )
    op.create_table(
        "evidence",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("engagement_id", sa.UUID(), nullable=False),
        sa.Column("source_type", sa.String(length=50), nullable=False),
        sa.Column("source_ref", sa.String(length=500), nullable=False),
        sa.Column("interview_id", sa.UUID(), nullable=True),
        sa.Column("dimension", sa.String(length=50), nullable=False),
        sa.Column("signal_type", sa.String(length=50), nullable=False),
        sa.Column("stage_hint", sa.Integer(), nullable=True),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("accepted_by", sa.UUID(), nullable=True),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["accepted_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["engagement_id"], ["engagements.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["interview_id"],
            ["interviews.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_evidence_dimension"), "evidence", ["dimension"], unique=False)
    op.create_index(op.f("ix_evidence_engagement_id"), "evidence", ["engagement_id"], unique=False)
    op.create_index(op.f("ix_evidence_interview_id"), "evidence", ["interview_id"], unique=False)
    op.create_table(
        "survey_responses",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("survey_id", sa.UUID(), nullable=False),
        sa.Column("engagement_id", sa.UUID(), nullable=False),
        sa.Column("anon_id", sa.String(length=64), nullable=False),
        sa.Column("team", sa.String(length=255), nullable=True),
        sa.Column("tenure_band", sa.String(length=50), nullable=True),
        sa.Column("role_category", sa.String(length=100), nullable=True),
        sa.Column("responses", postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "submitted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["engagement_id"], ["engagements.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["survey_id"], ["surveys.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_survey_responses_anon_id"), "survey_responses", ["anon_id"], unique=True
    )
    op.create_index(
        op.f("ix_survey_responses_engagement_id"),
        "survey_responses",
        ["engagement_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_survey_responses_survey_id"), "survey_responses", ["survey_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_survey_responses_survey_id"), table_name="survey_responses")
    op.drop_index(op.f("ix_survey_responses_engagement_id"), table_name="survey_responses")
    op.drop_index(op.f("ix_survey_responses_anon_id"), table_name="survey_responses")
    op.drop_table("survey_responses")
    op.drop_index(op.f("ix_evidence_interview_id"), table_name="evidence")
    op.drop_index(op.f("ix_evidence_engagement_id"), table_name="evidence")
    op.drop_index(op.f("ix_evidence_dimension"), table_name="evidence")
    op.drop_table("evidence")
    op.drop_index(op.f("ix_connector_runs_engagement_id"), table_name="connector_runs")
    op.drop_index(op.f("ix_connector_runs_connector_id"), table_name="connector_runs")
    op.drop_table("connector_runs")
    op.drop_index(op.f("ix_surveys_engagement_id"), table_name="surveys")
    op.drop_table("surveys")
    op.drop_index(op.f("ix_scores_engagement_id"), table_name="scores")
    op.drop_index(op.f("ix_scores_dimension"), table_name="scores")
    op.drop_table("scores")
    op.drop_index(op.f("ix_interviews_engagement_id"), table_name="interviews")
    op.drop_index(op.f("ix_interviews_created_by"), table_name="interviews")
    op.drop_table("interviews")
    op.drop_index(op.f("ix_exports_exported_by"), table_name="exports")
    op.drop_index(op.f("ix_exports_engagement_id"), table_name="exports")
    op.drop_table("exports")
    op.drop_index(op.f("ix_deliverables_engagement_id"), table_name="deliverables")
    op.drop_table("deliverables")
    op.drop_index(op.f("ix_connectors_engagement_id"), table_name="connectors")
    op.drop_table("connectors")
    op.drop_index(op.f("ix_audit_logs_user_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_engagement_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_created_at"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_action"), table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index(op.f("ix_artifacts_uploaded_by"), table_name="artifacts")
    op.drop_index(op.f("ix_artifacts_engagement_id"), table_name="artifacts")
    op.drop_table("artifacts")
    op.drop_index(op.f("ix_engagements_template_id"), table_name="engagements")
    op.drop_table("engagements")
    op.drop_index(op.f("ix_engagement_templates_created_by"), table_name="engagement_templates")
    op.drop_table("engagement_templates")
    op.drop_index(op.f("ix_users_google_sub"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
